name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.2'
      - run: flutter pub get
      - run: flutter test
        with:
          name: cypress-cucumber-report
          path: todomvc-typescript-react/cypress/cucumber-report/
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: learn-cypress-cucumber-reports
          source_dir: 'todomvc-typescript-react/cypress/cucumber-report'
      - name: Link to report
        run: echo "https://learn-cypress-cucumber-reports.s3-ap-southeast-2.amazonaws.com/${{steps.S3.outputs.object_key}}/index.html"