name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: flutter run
        with:
          java-version: '12.x'
          uses: subosito/flutter-action@v1
          flutter-version: '2.2.2'
        with:
          working-directory: report
          install-command: flutter pub get
          