
name: Test Report

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

jobs:
  report:
    name: Workflow test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2         # checkout the repo
      - run: flutter pub get              # install packages
      - run: flutter test  # run tests (configured to use jest-junit reporter)
      - uses: actions/upload-artifact@v2  # upload test results
        if: success() || failure()        # run this step even if previous step failed
      with:
        artifact: test-results
        name: Workflow Report
        path: 'reports/Report_test*.xml'
        reporter: jest-junit
        file_reporters:
  json: reports/test-results.json
